  0%|                                                                                                                            | 0/4 [00:00<?, ?it/s]Traceback (most recent call last):
data num:8
keys:dict_keys(['input_ids', 'labels'])
data num:8
keys:dict_keys(['input_ids', 'labels'])
data num:8
keys:dict_keys(['input_ids', 'labels'])
data num:8
keys:dict_keys(['input_ids', 'labels'])
data num:8
keys:dict_keys(['input_ids', 'labels'])
  File "/mnt/zhaorunsong/repository/ReCMLLM/train.py", line 77, in <module>
    trainer.train()
  File "/mnt/zhaorunsong/anaconda3/envs/ReCMLLM/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/mnt/zhaorunsong/anaconda3/envs/ReCMLLM/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/mnt/zhaorunsong/anaconda3/envs/ReCMLLM/lib/python3.10/site-packages/transformers/trainer.py", line 3579, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/mnt/zhaorunsong/repository/ReCMLLM/train.py", line 37, in compute_loss
    output = model(inputs=inputs["input_ids"], labels=inputs["labels"], num_items_in_batch=torch.tensor([num_items_in_batch for _ in range(bsz, dtype=torch.long)]))
TypeError: range() takes no keyword arguments
